[package]
name = "webdis-rs"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[dependencies]
iron = "*"
redis = "*"
r2d2 = "*"
r2d2_redis = { git = "https://github.com/badboy/r2d2-redis", branch = "cache-connection"}
