[package]
name = "webdis-rs"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[dependencies]
iron = "*"
redis = "*"
r2d2 = "*"
r2d2_redis = { path = "/home/badboy/code/rust/r2d2-redis", branch = "newer-redis"}
